### ISSUE TITLE
Integrate spark streaming with StreamCQL

### ISSUE THREAD

**Issue by zhutongxue** [HuaweiBigData/StreamCQL#10]
Spark streaming is another popular stream computation platform,and spark community is very active ,we can consider integrate spark streaming with StreamCQL.

**Comment by Zhiqiang-He** [comment]
we are very glad to see it.  we will add you to developer if you want develop StreamCQL on spark streaming.

**Comment by huawei-bigdata** [comment]
@zhutongxue
Could you leave me your weixin account, so we can add you into our streamcql group.
BTW, I am responsible for opensource affair in HUAWEI.

thanks:)

**Comment by zhutongxue** [comment]
@Zhiqiang-He 
zhuguanghui1105  my weixin account， sorry to response so late !!
