### ISSUE TITLE
about "explain application "

### ISSUE THREAD

**Issue by makebest** [HuaweiBigData/StreamCQL#18]
按照例子2，创建了kafka的application，执行正常，但是查看执行计划，看不到cql，这个正常吗？

还有其他的方法可以看到application里面的cql吗？
执行如下：

Streaming>CREATE INPUT STREAM s1
>    (name STRING)
>SOURCE RANDOMGEN
>    PROPERTIES ( timeUnit = "SECONDS", period = "1",
>        eventNumPerperiod = "1", isSchedule = "true" );
Streaming>
>CREATE OUTPUT STREAM s2
>    (c1 STRING)
>SINK kafkaOutput
>    PROPERTIES ( topic = "mytopic", zookeepers = "172.18.24.53:2181",
>        brokers = "172.18.24.53:9092" );
Streaming>
>CREATE INPUT STREAM s3
>    ( c1 STRING)
>SOURCE KafkaInput
>    PROPERTIES (groupid = "test-consumer-group", topic = "mytopic",
>        zookeepers = "172.18.24.53:2181", brokers = "172.18.24.53:9092" );
Streaming>
>CREATE OUTPUT STREAM s4
>    (c1 STRING)
>SINK consoleOutput;
Streaming>
>INSERT INTO STREAM s2 SELECT * FROM s1;
Streaming>INSERT INTO STREAM s4 SELECT * FROM s3;
Streaming>
>SUBMIT APPLICATION cql_kafka_example;
Streaming>explain application cql_kafka_example;
stringApp

"《Definitions》
  《Application id="cql_kafka_example"》
    《Schemas/》
   《Operators/》
  《Transitions/》
 《/Application》
《/Definitions》
"

Streaming>

**Comment by Zhiqiang-He** [comment]
@makebest 
执行计划是要在CQL语句没有提交之前使用的，作用是将当前未提交的语句进行编译分析，生成拓扑图，并以XML的方式打印在控制台或者文件中。
一旦执行了submit，当前所有用户提交的语句都会被清空，所以才会导致explain的时候没有输出。
可以先执行explain，再执行submit。

**Comment by makebest** [comment]
有两个问题请教下：
（1）有没有办法看到某个Application里面包含的CQL。
（2）能否为某个CQL Application指定资源（worker,executeNum,taskNum等）

**Comment by Zhiqiang-He** [comment]
1、已经提交到Storm上的application没办法看到对应的CQL
2、CQL可以指定worker number和taskNumber，但是无法指定executorNumber。
worker number可以通过参数：streaming.storm.worker.number指定，默认是1.
taskNumber可以通过parallel语法来设置。可以精确为每个算子设置不同的并发度。
