### ISSUE TITLE
First roadmap of StreamCQL has been published, we welcome you to be our project contributor.

### ISSUE THREAD

**Issue by huawei-bigdata** [HuaweiBigData/StreamCQL#22]
Roadmap by @Zhiqiang-He is here:  
https://github.com/HuaweiBigData/StreamCQL/blob/master/RoadMap_CN.md

We welcome you contributing to the project, idea, code, bug fix, doc, test, any you want is welcome, just do it.
you can contanct @Zhiqiang-He or zhang__xiaopeng(weixin ID), then we can talk about the plan and other details. Give your opion in this issue is also welcome.

Thanks and we look forward your join.

**Comment by zhengzf** [comment]
当前的版本不支持窗口分组,排序这些功能，什么时候能加上？

**Comment by Zhiqiang-He** [comment]
@zhengzf 在1.1版本的RoadMap中暂时没有支持排序窗口的计划，如果大家有相关功能反馈，并且有使用需求，我们会考虑添加的。
