### ISSUE TITLE
multiInsert语句

### ISSUE THREAD

**Issue by zhengzf** [HuaweiBigData/StreamCQL#23]
from pageview
insert into stream aliasPageView select cast(context__page as int) as pageid , context__url as url,user__id as userid 
insert into stream userid_stream select user__id as userid;
用multiinsert语句创建你两个流aliasPageView，userid_stream
insert into stream urls select patternstr(url,"(?<=/p)[0-9]*") as productid,userid from aliasPageView where pageid in (221080,220080,401019）
再从aliasPageView中取数据，提交任务后会提示找不到aliasPageView
查看代码发现mutliInsert没有对应SemanticAnalyzeHook类把schema信息加到全局的DriverContext中，导致会有这个错误。
请问下这个是bug还是我语法写的问题，如果是bug大概什么时候能解决？

**Comment by Zhiqiang-He** [comment]
这个确实是CQL的一个bug，感谢指出，我们会尽快修复。希望今天可以解决。

**Comment by Zhiqiang-He** [comment]
@zhengzf  问题已经解决。

**Comment by zhengzf** [comment]
恩,已经能提交了。3q

**Comment by zhengzf** [comment]
@@ -471,7 +471,7 @@ public class ApplicationBuilder
             {
                 if (!mInsert.isPipeStreamNotCreated())
                 {
-                    return;
+                    continue;
                 }

我这边还做了这个修改，如果multi语句分割的时候包括一个outputStream，应该继续检查而不是返回把。

**Comment by Zhiqiang-He** [comment]
@zhengzf  已经合入，感谢指出。

**Comment by Zhiqiang-He** [comment]
https://github.com/HuaweiBigData/StreamCQL/pull/25
