### ISSUE TITLE
使用一个无输入的output stream组件问题

### ISSUE THREAD

**Issue by zhengzf** [HuaweiBigData/StreamCQL#28]
我在一段脚本里创建了个topoloy，然后有一个无用的output stream组件。
提交可以完成，但是storm作业在运行时会报java.lang.NullPointerException，查看代码
ExecutorPlanGenerator类的combineOperator方法只检测Transition，
for (OperatorTransition ot : apiApplication.getOpTransition())
但是无用的output stream组件不在这个遍历查找范围里，所以没有设置conf，当bolt启动时
prepare函数会取查找conf的字段，导致报java.lang.NullPointerException。
虽然逻辑上不会创建一个无用的output stream组件。

**Comment by Zhiqiang-He** [comment]
可以把你的CQL语法发一下吗？我来看下执行计划。
发我邮箱都可以。就用github上的这个邮箱地址。

**Comment by zhengzf** [comment]
我加了自定义的datasource，所以整个脚本发过去也执行不了。
随便拿一个可执行的cql脚本，然后加一句
create output stream console_h5 (uid String,destcity String) SINK consoleOutput;
这样就应该能重现了。

**Comment by zhengzf** [comment]
另外，问下你们之后会适配jstorm吗？

**Comment by Zhiqiang-He** [comment]
@zhengzf 问题已经重现出来了，确实如此，正常提交没有问题，但是运行时候会有问题。
这种拓扑实际上应该是不允许提交的。不过不论是storm还是cql都没有检测出来。
Bolt不应该单独存在。必须依赖于其他的bolt或者spout。 这个我会对拓扑进行检查的。感谢指出这个问题。

**Comment by Zhiqiang-He** [comment]
@zhengzf 关于jstorm的适配，目前看起来不会了。原因有两点：
1、社区JStorm和Storm2.0版本的合并，这样看起来对JStorm的支撑意义就不大了。
2、Heron的开源，CQL会对这个提供适配。

**Comment by Zhiqiang-He** [comment]
@zhengzf 可以留下你的微信吗？有时候github消息没办法及时回复，微信会方便很多。

**Comment by zhengzf** [comment]
@Zhiqiang-He 好的，微信号:zhengzfand

**Comment by Zhiqiang-He** [comment]
@zhengzf 抱歉，微信号码搜不到用户，麻烦再检查下是否拼写错误。

**Comment by zhengzf** [comment]
@Zhiqiang-He 之前没开通过微信号添加。现在再试试
