### ISSUE TITLE
self join的问题

### ISSUE THREAD

**Issue by zhengzf** [HuaweiBigData/StreamCQL#31]
创建了一个self join了例子
create input stream owl_monitor_new(orderid String,ordercreateTime String) source consoleInput;
create output stream owl_monitor_distinct(orderid String,OrderCreateTime String,count int) sink ConsoleOutput;
insert into owl_monitor_distinct select s1.OrderID,s1.OrderCreateTime,count(s1.orderid) as c from owl_monitor_new[ range 60 seconds slide ] as s1 UNIDIRECTION inner join
owl_monitor_new  as s2 on s1.OrderID=s2.OrderID group by s1.OrderID,s1.OrderCreateTime having c=1 ;
submit application testJoin;
这个是可以运行的，目的是最近一分钟内的数据不重复。
但是将输入流改为非input stream时，无法通过，比如以下脚本：
create input stream owl_monitor_input(orderid String,ordercreateTime String) source consoleInput;
create output stream owl_monitor_distinct(orderid String,OrderCreateTime String,count int) sink ConsoleOutput;
insert into owl_monitor_new select \* from monit_input;
insert into owl_monitor_distinct select s1.OrderID,s1.OrderCreateTime,count(s1.orderid) as c from owl_monitor_new[ range 60 seconds slide ] as s1 UNIDIRECTION inner join
owl_monitor_new  as s2 on s1.OrderID=s2.OrderID group by s1.OrderID,s1.OrderCreateTime having c=1 ;
submit application testJoin;

麻烦看下是否能解决。

**Comment by Zhiqiang-He** [comment]
这个是selfjoin的bug。
移除过滤语句就可以了。
create input stream owl_monitor_new(orderid String,ordercreateTime String) source consoleInput;
create output stream owl_monitor_distinct(orderid String,OrderCreateTime String,count int) sink ConsoleOutput;
--insert into owl_monitor_new select * from owl_monitor_input;
insert into owl_monitor_distinct select s1.OrderID,s1.OrderCreateTime,count(s1.orderid) as c from owl_monitor_new[ range 60 seconds slide ] as s1 UNIDIRECTION inner join
owl_monitor_new as s2 on s1.OrderID=s2.OrderID group by s1.OrderID,s1.OrderCreateTime having c=1 ;
submit application testJoin;

**Comment by Zhiqiang-He** [comment]
如果需要过滤，可以使用窗口之前的过滤，比如：
	--filter before window selft join
insert into stream rs select s.id,s.name,s2.type from S[range today type] join S(s.id>10)[range unbounded] as s2 unidirection on s.id = s2.id where s.id > 5;

**Comment by zhengzf** [comment]
恩，我们现在也是这么解决的

**Comment by zhengzf** [comment]
那这样的话selfjoin只能是input stream？
