### ISSUE TITLE
consoleOutput无输出

### ISSUE THREAD

**Issue by BYRans** [HuaweiBigData/StreamCQL#32]
您好，我使用Kafka输入源、console输出，但是看不到输出

CREATE INPUT STREAM s3
    ( c1 STRING)
SOURCE KafkaInput
PROPERTIES (groupid = "dingyuTestCQL", topic = "test", zookeepers = "172.16.18.250:2181/kafka", brokers = "172.16.18.250:9092");
CREATE OUTPUT STREAM s4
    (c1 STRING)
SINK consoleOutput
PROPERTIES(printFrequence = "10");
INSERT INTO STREAM s4 SELECT \* FROM s3;
SUBMIT APPLICATION cql_kafka_example;

**Comment by Zhiqiang-He** [comment]
因为CQL提交拓扑之后，就和storm断开了连接，所以，console output实际上指的就是日志文件的输出，在拓扑的日志文件中可以看到输出结果。

**Comment by chgxtony** [comment]
console output实际上指的就是日志文件的输出 , 能说的具体点吗，我没看到具体的输出啊

**Comment by Zhiqiang-He** [comment]
consoleOutput 会将结果输出到Storm的worker所在的日志文件中，为info级别，所以你看下storm的worker日志文件。

**Comment by chgxtony** [comment]
谢谢，找到了
