### ISSUE TITLE
IN / LIKE 等关键词支持情况？

### ISSUE THREAD

**Issue by BYRans** [HuaweiBigData/StreamCQL#33]
您好，请问StreamCQL当前是不是不支持IN、LIKE这几个关键词？
我看到语法手册中的目录上有这几个关键词的介绍目录，但是在文档中没有相应的章节，在终端输入带有IN关键词的语句也会报错。

**Comment by Zhiqiang-He** [comment]
这些表达式在我们新版本里面已经支持了，但是还没有更新上来，在CQL的下个版本中会包含。

**Comment by BYRans** [comment]
哇~赞~
新版本，预计什么时间更新？

**Comment by Zhiqiang-He** [comment]
目前事务比较多一些，一直没有来得及更新。最新的更新时间大概在9月份吧。具体时间还没有定下来。
