### ISSUE TITLE
使用set设置配置参数不起作用？

### ISSUE THREAD

**Issue by naichunW** [HuaweiBigData/StreamCQL#34]
在cql命令行中，使用   set "topology.workers"=“20”;   后提交任务，依然是默认值1。

**Comment by Zhiqiang-He** [comment]
应该是这个配置参数：
  /**
     * Storm任务的worker数量
     */
    public static final String STREAMING_STORM_WORKER_NUMBER = "streaming.storm.worker.number";

https://github.com/HuaweiBigData/StreamCQL/blob/master/streaming/src/main/java/com/huawei/streaming/config/StreamingConfig.java#L141
