### ISSUE TITLE
提示java.lang.NoClassDefFoundError: com/huawei/streaming/operator/IInputStreamOperator

### ISSUE THREAD

**Issue by hellolintong** [HuaweiBigData/StreamCQL#35]
你好，我在使用StreamCQL的时候，依照文档的介绍，使用了自定义的FileInput类获取数据，但是查看日志发现如下错误：
2016-08-23 22:04:38.124 b.s.d.worker [ERROR] Error on initialization of server mk-worker
java.lang.NoClassDefFoundError: com/huawei/streaming/operator/IInputStreamOperator
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_79]
我想问下，如何在pom文件中引入对应的类呢？

**Comment by Zhiqiang-He** [comment]
这个错误发生在worker运行时还是在自定义fileInput的编译过程中？编译过程中的话，需要引入streaming的jar包。

**Comment by hellolintong** [comment]
麻烦问下，streaming的jar包的maven地址是多少？需要自己手动生成jar包然后手动include吗？

**Comment by hellolintong** [comment]
能要下你的联系方式吗？有些问题方便沟通下；

**Comment by Zhiqiang-He** [comment]
Streaming在CQL编译中可以获得。需要自己手工编译
微信号：absolute005
