### ISSUE TITLE
在parallel=10的情况下count会输出10个值

### ISSUE THREAD

**Issue by naichunW** [HuaweiBigData/StreamCQL#36]
想统计5秒内消息的条数，使用如下语句：
insert into s4 select count(*) from s3[range 5 seconds batch] parallel 10;
s4是KafkaOutput，这样每5秒会数据10个值。

**Comment by Zhiqiang-He** [comment]
因为并发度是10，所以有10个算子去完成，相当于有10个滑动窗的实例。
