### ISSUE TITLE
支持Storm 1.0版本吗？

### ISSUE THREAD

**Issue by BYRans** [HuaweiBigData/StreamCQL#37]
您好，请问StreamCQL能不能兼容1.0版本，您这边有测试过吗？
另外，您在使用StreamCQL时，是怎么Storm进行资源管理的？

**Comment by Zhiqiang-He** [comment]
我们这边还没有切换到1.0版本，目前CQL还是不支持的。
不过storm的版本应该是兼容的，你可以修改下依赖编译下试试看。
storm的资源管理，我们还是使用的supervisor，和社区一样。

**Comment by Zhiqiang-He** [comment]
@BYRans ,CQL 2.0版本已经发布了，支持Storm 1.0版本。
