### ISSUE TITLE
Wrong spelling in source code.

### ISSUE THREAD

**Issue by lexchou** [HuaweiBigData/StreamCQL#4]
https://github.com/HuaweiBigData/StreamCQL/blob/master/cql/src/main/java/com/huawei/streaming/cql/semanticanalyzer/SelectClauseAnalyzer.java

单词拼写错误：
    private AtomExpressionContext craeteAtomExpression(String columnName)

**Comment by Zhiqiang-He** [comment]
@lexchou 
    Can you help us to fix it ? thanks.

**Comment by jan4984** [comment]
蛋疼...
