### ISSUE TITLE
请问：fieldsGrouping 怎么实现

### ISSUE THREAD

**Issue by dongyanfeng** [HuaweiBigData/StreamCQL#40]
请问fieldsGrouping 用sql怎么写呢？

**Comment by Zhiqiang-He** [comment]
没有直接的fieldsGrouping语法，使用group by或者Join的语法，内部就会默认使用fieldsGrouping ，否则都是localorshuffle

**Comment by dongyanfeng** [comment]
谢谢。
请问时间窗口可以根据数据时间来处理吗？

**Comment by Zhiqiang-He** [comment]
目前版本还不支持该功能，这个功能我们已经开发完毕，会在下个版本中发布，时间大概在11月份吧。
