### ISSUE TITLE
请问：窗口可以针对日志时间吗？

### ISSUE THREAD

**Issue by dongyanfeng** [HuaweiBigData/StreamCQL#41]
窗口是在数据处理时间上的操作，能针对日志时间做操作吗？谢谢

**Comment by Zhiqiang-He** [comment]
目前版本还不支持该功能，这个功能我们已经开发完毕，会在下个版本中发布，时间大概在11月份吧。
这个功能就是基于事件时间驱动的窗口。

**Comment by dongyanfeng** [comment]
请问新的版本开发完了吗？

**Comment by Zhiqiang-He** [comment]
主体功能都已经开发完毕了，还在测试中，等上传大概要到12月初了。

**Comment by Zhiqiang-He** [comment]
@dongyanfeng StreamCQL 2.0版本已经发布，欢迎试用。
https://github.com/HuaweiBigData/StreamCQL/releases

**Comment by dongyanfeng** [comment]
如果数据流里面event_time出现乱序的数据，用event_time做的聚合运算就不正确了。

**Comment by Zhiqiang-He** [comment]
那就用时间排序窗口，先对乱序数据做排序处理。
