### ISSUE TITLE
时间窗口能加上触发条件吗？

### ISSUE THREAD

**Issue by zhengzf** [HuaweiBigData/StreamCQL#42]
目前的版本是根据消息事件触发的，是否能增加一个根据指定时间触发计算的功能，或者触发条件？

**Comment by Zhiqiang-He** [comment]
窗口是持续存在的，不会包含触发条件的。
其实感觉你要的模式匹配。
当某一个特定条件满足的时候，检查这个时间点之前或者之后一段时间或者一定数据中的内容是否满足某哥特征。
模式匹配我们这个版本还是不支持的。

**Comment by zhengzf** [comment]
差不多是这样，比较简单的例子是每半个小时做一次聚合计算。现在的版本的话我需要写两句以上的cql才能实现这个功能。
那希望尽快支持吧
