### ISSUE TITLE
关于com.huawei.streaming.cql.Driver的 开发

### ISSUE THREAD

**Issue by darouwan** [HuaweiBigData/StreamCQL#44]
我打算在一个独立程序中使用Driver的run方法提交一个application。现在遇到一个问题，即使仿造bin/cql中添加了所有的classpath，运行我自己的程序也正常显示Finished submitting topology：***。 但查看日志文件，显示异常：
2016-11-30 15:41:21.478 b.s.d.worker [ERROR] Error on initialization of server mk-worker
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.huawei.streaming.storm.StormSpout
看起来还是storm相关的类没有加载进来。

不知道是不是我操作方法有问题？还是有什么地方没注意？

**Comment by Zhiqiang-He** [comment]
这个日志是在storm的worker中抛出来的吗？可能是因为你的classpath中没有添加dependency jar导致的。
你看下脚本，里面会添加一个cql.dependency.jar这个系统变量，这个系统变量就是cql运行时候的依赖包，
sbumit application的时候，它会将你自己add jar的文件和这个dependency jar进行合并，然后提交。

**Comment by darouwan** [comment]
是的，worker里跑出来的。那我dependency jar，应该是添加原来的stream storm那个包，还是我自己写的这个包？

**Comment by Zhiqiang-He** [comment]
添加CQL编译出来的那个jar包。
在tar.gz文件中有这个文件。

**Comment by darouwan** [comment]
就是这个吗 ？stream-storm-1.0-jar-with-dependencies.jar

**Comment by darouwan** [comment]
好了，可以正常运行，谢谢
