### ISSUE TITLE
时间跳动窗的输出问题

### ISSUE THREAD

**Issue by darouwan** [HuaweiBigData/StreamCQL#45]
最近测试时间跳动窗的时候，发现一个问题：
比如执行如下查询：
INSERT INTO STREAM s2 select cint, count(*) from S1[range 10 seconds batch] group by cint;

如果持续向S1输入数据，那么S2可以读取到S1输入的原数据，并且妹10秒可以得到一次统计数据。但如果停止向S1输入数据，那么count(*)仍然会输出一次为0的记录，然后停止输出。是本来就这样设计的吗？

**Comment by Zhiqiang-He** [comment]
设计就是这样的，时间跳动窗口中是否输出数据，取决于窗口内数据有没有发生变化。
当停止输入的时候，等10秒钟，窗口内有数据过期，统计结果就会发生变化，所以自然会有一次输出。

**Comment by darouwan** [comment]
好的，谢谢。处理时间跳动窗是在哪个类里面？

**Comment by Zhiqiang-He** [comment]
EventTimeBatchWidnow.java

**Comment by darouwan** [comment]
thx~
