### ISSUE TITLE
事件驱动窗口文档

### ISSUE THREAD

**Issue by zhengzf** [HuaweiBigData/StreamCQL#46]
6、支持事件驱动窗口（包含事件驱动滑动窗，事件驱动跳动窗，事件驱动分组滑动窗，事件驱动分组跳动窗，时间排序窗），以及自然天窗口和分组自然天窗口

这条有相关的文档吗？

**Comment by Zhiqiang-He** [comment]
CQL语法手册中包含该窗口描述

https://github.com/HuaweiBigData/StreamCQL/blob/master/doc/cn/CQL%E8%AF%AD%E6%B3%95%E6%89%8B%E5%86%8C.docx

可以把整个工行的zip包down下来看，直接从这个链接下载有问题，打不开。
