### ISSUE TITLE
请问如何查看生成的拓扑任务的源码

### ISSUE THREAD

**Issue by dyaodwjh** [HuaweiBigData/StreamCQL#48]
请问如何查看生成的拓扑任务的源码呢?

**Comment by Zhiqiang-He** [comment]
拓扑生成的源码就在Streaming目录中。
https://github.com/HuaweiBigData/StreamCQL/tree/master/streaming
StreamCQL走的不是代码生成的路子，所以不存在找不到的代码。
你可以通过explain命令来查看到执行计划，执行计划中用到的每个算子都可以看到了。

**Comment by dyaodwjh** [comment]
好的,谢谢
