### ISSUE TITLE
应用重启如何保证中间临时状态的数据复原

### ISSUE THREAD

**Issue by yangsishu** [HuaweiBigData/StreamCQL#49]
就是在应用重启如何保证中间临时状态的数据复原，我这边看源码好像没有这方面的设计

**Comment by Zhiqiang-He** [comment]
CQL当前是不支持这种可靠性的。
主要是因为Storm的Acker机制对于窗口来说并不是很适用。
目前来说整个业界都还没有很好的可靠性机制能够在窗口中使用。
Flink的checkpoint机制storm还不支持。
用户可以自己将状态保存在共享存储过程数据库中来实现。
