### ISSUE TITLE
SimpleSerDe反序列化源数据时，字段数量不一致的问题

### ISSUE THREAD

**Issue by SuXingLee** [HuaweiBigData/StreamCQL#54]
使用SimpleSerDe时，如果源数据属性字段数量不等于 Input中定义的 schema，则无法解析，将会丢掉该条数据。
看了下源码，是BaseSerDe类的validateColumnSize(Object[] strArr) 对字段数量进行验证导致的。
在使用StreamCQL做ETL时，把在源数据上追加字段是很普遍的情况。是不是应该尽量正确解析源数据，而不是丢弃该条数据？

**Comment by Zhiqiang-He** [comment]
这种情况下不应该使用simpleserde，应该自定义来解决该问题。
或者在入口schema中就定义完整所有的列，然后在下一级的select中再去过滤。
