### ISSUE TITLE
关于streamcql启动时间的花费成本疑问？

### ISSUE THREAD

**Issue by zhangxin0112** [HuaweiBigData/StreamCQL#63]
你好。
在使用streamcql的时候，发现启动一个cql任务耗时达5分钟，开启log debug之后发现耗时主要在jar包文件解压，合并，拷贝中，经查看com.huawei.streaming.cql.executor.mergeuserdefinds.Merger类的注释是
“Storm中只允许提交一个用户jar包，所以这就要求将所有的用户自定义jar包和文件打包在一个新的文件中，storm才可以加载。”
经查看storm官方文档关于jar包的加载的命令行jar描述是如下：
http://storm.apache.org/releases/1.1.0/Command-line-client.html
不知是之前版本的差异还是这是可以改进的地方呢？

**Comment by Zhiqiang-He** [comment]
这个是在Storm 1.1版本才开始有的。 storm目前还支持该版本，没有在该版本上做过测试。
我暂时还没有看过这个功能的内部实现时怎么样的，所以也没办法提出修改建议，你可以自己参照storm的实现方式来做修改。欢迎在修改完毕之后提交merge reqeust。

**Comment by zhangxin0112** [comment]
谢谢回复。
:+1:
