### ISSUE TITLE
Stream CQL Mutil Version

### ISSUE THREAD

**Issue by darionyaphet** [HuaweiBigData/StreamCQL#7]
Apache Storm release 0.10.0 at recently . But a lot of Storm Cluster is 0.9.X .

Would we modify Mavem pom and specified storm version when packaging?

`I try to transfer CQL to Storm 0.9.4 and I found AuthorizationException Not Found `

**Comment by Zhiqiang-He** [comment]
StreamCQL is based on Storm 0.10.0 because security.
if you want to used in Storm 0.9.4. you can download code  and remove AuthorizationException  in adapter/storm package.

**Comment by Zhiqiang-He** [comment]
It is not a issues. i will close it.
