### ISSUE TITLE
mvn clean install 完成之后没有cql-binary/target目录生成

### ISSUE THREAD

**Issue by talialulu** [HuaweiBigData/StreamCQL#71]
用的是streamCQL2.0,执行了 ，mvn clean install之后没有看到cql-binary/target是什么情况

**Comment by Zhiqiang-He** [comment]
在cql-binary/storm/target，或者其他storm-0.10/target的目录下, 如果都没有的话，确认下是不是编译失败，或者在binary的制定目录下单独执行install命令。
