### ISSUE TITLE
窗口滑动间隔如何自定义

### ISSUE THREAD

**Issue by jessica0530** [HuaweiBigData/StreamCQL#74]
SQL层面上面用户不能设置窗口滑动间隔时间,代码中也是写死的5ms,这个设计的用意是什么
public class TimeSlideWindowCreator implements WindowCreator
{
    
    private static final long SLIDE_INTERVAL = 5;
}

**Comment by Zhiqiang-He** [comment]
滑窗间隔目前还不能设置，这个参数接口是预留的，这个功能目前还没有实现。StreamCQL目前还不支持翻滚窗。
