### ISSUE TITLE
咨询个语法问题，如何解决

### ISSUE THREAD

**Issue by caiyifeng** [HuaweiBigData/StreamCQL#76]
您好：
  我定义了两个输入流 S1,S2，当我使用如下语法的时候会有问题：
insert into s3 select *,null from S1;
insert into s3 select *,1 from S2;
不能合并到同一个临时流S3
我发现报错的信息如下：
Failed to assign Fail to sumbit topology Failed to deserilaize Union_013 json configuration: {"streaming.inner.input.stream.name":"st_008","operator.union.inputnames.and.schema":{"st_008":s3,"st_006":s3},"streaming.storm.nimbus.port":"8627","operator.tcpclient.sessiontimeout":"20000","streaming.userfile.maxsize":"50","operator.kafka.zksynctime":"20000","streaming.storm.ha.zksessiontimeout":"30000","operator.headstream.period":"1","operator.headstream.eventnumperperiod":"1","serde.binaryserde.decimaltype":"DECIMAL","streaming.security.zookeeper.principal":"zookeeper\/hadoop","streaming.storm.ha.zkaddress":"10.139.32.187","streaming.serde.default":"com.huawei.streaming.serde.SimpleSerDe","streaming.inner.output.stream.name":"st_003","operator.headstream.delaytime":"0","operator.kafka.messageserializerclass":"kafka.serializer.StringEncoder","operator.kafka.zksessiontimeout":"20000","datasource.rdb.decrypttype":"ALL","serde.keyvalueserde.separator":",","serde.field.ismapping":"false","streaming.storm.worker.number":"1","streaming.killapplication.overtime":"30","streaming.security.storm.principal":"streaming\/hadoop@HADOOP.COM","streaming.inner.input.schema":"rO0ABXNyACljb20uaHVhd2VpLnN0cmVhbWluZy5ldmVudC5UdXBsZUV2ZW50VHlwZTqNoJEQsNqiAgAGSQAEc2l6ZVsACGF0dE5hbWVzdAATW0xqYXZhL2xhbmcvU3RyaW5nO1sACGF0dFR5cGVzdAASW0xqYXZhL2xhbmcvQ2xhc3M7TAAFYXR0aWR0ABNMamF2YS91dGlsL0hhc2hNYXA7TAAEbmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO1sABnNjaGVtYXQAJ1tMY29tL2h1YXdlaS9zdHJlYW1pbmcvZXZlbnQvQXR0cmlidXRlO3hwAAAABHVyABNbTGphdmEubGFuZy5TdHJpbmc7rdJW5+kde0cCAAB4cAAAAAR0AAJpZHQABG5hbWV0AAR0eXBldAAHbnVsbGNvbHVyABJbTGphdmEubGFuZy5DbGFzczurFteuy81amQIAAHhwAAAABHZyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHBxAH4AEXEAfgARdnIAEGphdmEubGFuZy5TdHJpbmeg8KQ4ejuzQgIAAHhwc3IAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJdGhyZXNob2xkeHA\/QAAAAAAADHcIAAAAEAAAAARxAH4ADHNxAH4ADwAAAANxAH4ACnNxAH4ADwAAAAFxAH4ACXNxAH4ADwAAAABxAH4AC3NxAH4ADwAAAAJ4dAACczN1cgAnW0xjb20uaHVhd2VpLnN0cmVhbWluZy5ldmVudC5BdHRyaWJ1dGU7WE5islwJ+0MCAAB4cAAAAARzcgAkY29tLmh1YXdlaS5zdHJlYW1pbmcuZXZlbnQuQXR0cmlidXRldPFuTyvGASsCAAJMAAthdHREYXRhVHlwZXQAEUxqYXZhL2xhbmcvQ2xhc3M7TAAHYXR0TmFtZXEAfgAEeHBxAH4AEXEAfgAJc3EAfgAdcQB+ABFxAH4ACnNxAH4AHXEAfgARcQB+AAtzcQB+AB1xAH4AE3EAfgAM","streaming.storm.ha.zkroot":"\/jstorm333","operator.kafka.zookeepers":"127.0.0.1:2181","streaming.security.authentication":"NONE","streaming.storm.rebalance.waitseconds":"10","streaming.operator.timezone":"Asia\/Shanghai","streaming.adaptor.application":"com.ctrip.streaming.jstorm.JStormApplication","streaming.storm.thrift.transport.plugin":"backtype.storm.security.auth.SimpleTransportPlugin","serde.simpleserde.separator":",","operator.kafka.read.frombeginning":"false","operator.kafka.brokers":"127.0.0.1:21802","streaming.inner.output.schema":"rO0ABXNyACljb20uaHVhd2VpLnN0cmVhbWluZy5ldmVudC5UdXBsZUV2ZW50VHlwZTqNoJEQsNqiAgAGSQAEc2l6ZVsACGF0dE5hbWVzdAATW0xqYXZhL2xhbmcvU3RyaW5nO1sACGF0dFR5cGVzdAASW0xqYXZhL2xhbmcvQ2xhc3M7TAAFYXR0aWR0ABNMamF2YS91dGlsL0hhc2hNYXA7TAAEbmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO1sABnNjaGVtYXQAJ1tMY29tL2h1YXdlaS9zdHJlYW1pbmcvZXZlbnQvQXR0cmlidXRlO3hwAAAABHVyABNbTGphdmEubGFuZy5TdHJpbmc7rdJW5+kde0cCAAB4cAAAAAR0AAJpZHQABG5hbWV0AAR0eXBldAAHbnVsbGNvbHVyABJbTGphdmEubGFuZy5DbGFzczurFteuy81amQIAAHhwAAAABHZyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHBxAH4AEXEAfgARdnIAEGphdmEubGFuZy5TdHJpbmeg8KQ4ejuzQgIAAHhwc3IAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJdGhyZXNob2xkeHA\/QAAAAAAADHcIAAAAEAAAAARxAH4ADHNxAH4ADwAAAANxAH4ACnNxAH4ADwAAAAFxAH4ACXNxAH4ADwAAAABxAH4AC3NxAH4ADwAAAAJ4dAACczN1cgAnW0xjb20uaHVhd2VpLnN0cmVhbWluZy5ldmVudC5BdHRyaWJ1dGU7WE5islwJ+0MCAAB4cAAAAARzcgAkY29tLmh1YXdlaS5zdHJlYW1pbmcuZXZlbnQuQXR0cmlidXRldPFuTyvGASsCAAJMAAthdHREYXRhVHlwZXQAEUxqYXZhL2xhbmcvQ2xhc3M7TAAHYXR0TmFtZXEAfgAEeHBxAH4AEXEAfgAJc3EAfgAdcQB+ABFxAH4ACnNxAH4AHXEAfgARcQB+AAtzcQB+AB1xAH4AE3EAfgAM","streaming.common.istestmodel":"true","datasource.rdb.decryptclass":"com.huawei.streaming.encrypt.DefaultDecrypt","operator.union.inner.inputnames.and.expression":{"st_008":[Lcom.huawei.streaming.expression.IExpression;@534ca02b,"st_006":[Lcom.huawei.streaming.expression.IExpression;@29a23c3d},"streaming.storm.nimbus.host":"10.139.32.185","operator.headstream.totalnumber":"0","streaming.storm.ha.zkport":"2181","streaming.localtask.alivetime.ms":"5000","streaming.storm.killtask.waitseconds":"3","streaming.template.directory":"C:\\Users\\CAIYIF~1\\AppData\\Local\\Temp\\","serde.binaryserde.timetype":"LONG","operator.headstream.isschedule":"false","streaming.storm.ha.zkconnectiontimeout":"30000","operator.consoleprint.frequence":"1","streaming.storm.submit.islocal":"false","operator.headstream.timeunit":"SECONDS"}, cause:null

**Comment by caiyifeng** [comment]
请问这个如何解决，请指教，多谢多谢

**Comment by Zhiqiang-He** [comment]
参照#77
