### ISSUE TITLE
怎么定义新的数据类型

### ISSUE THREAD

**Issue by caiyifeng** [HuaweiBigData/StreamCQL#78]
请问：
   目前在定义列的时候，支持的数据类型为String,Integer,Long。。。。等，，如果想自定义列的数据类型，如Map，该如何做?看过源码，但确实不太明白，希望能得到你们的指导，多谢，，，多谢

**Comment by Zhiqiang-He** [comment]
可以自定义数据类型，但是比较复杂，可以参照string，integer这些类型的实现。
建议使用字符串类型，然后用udf函数进行计算。

**Comment by caiyifeng** [comment]
好的，多谢
