### ISSUE TITLE
关于streamingcql中的一个语法问题，求解答 

### ISSUE THREAD

**Issue by caiyifeng** [HuaweiBigData/StreamCQL#81]
您好：
   咨询下，语法中关于自定义算子，有个语法如下：
insert into rs using operator userOp from s distribute by id parallel 2

请问其中的distribute by 是不是就是storm中的分组group？，，我试了下，发现只能支持单个字段，如果
insert into rs using operator userOp from s distribute by id,appname parallel 2 
多了个字段好像就不支持了

请问是否如此

**Comment by Zhiqiang-He** [comment]
是的，当前只支持单字段分发。对应就是storm中的group

**Comment by caiyifeng** [comment]
明白，多谢多谢！
